version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_NewgithubUsernameProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
